version: "3"
services:
  # he main service cluster manager
  zookeeper:
    container_name: "singlezookeper"
    hostname: clusterserver
    restart: always
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888

  # governs all the internal nodes clusters
  nifinodes:
    container_name: nifinodes # can have many nodes internally
    build: .
    image: nifi-node:1.0.1
    depends_on:
      - zookeeper
    volumes:
      - /home/synarcs/Downloads/nifi-1.12.1/conf:/opt/nifi/nifi-current/conf
    environment:
      # Used by ListenTCP or other processors. Depends on the data flow.
      - EXCLUDE_PORTS=8081,8082
      - TCP_PORTS=9001

  # can be replaced using EKS or external service
  Loadbalancer:
    image: dockercloud/haproxy
    container_name: "loadbalancer"
    restart: always
    links:
      - nifinodes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5555:80" # for nifi web api
      - "9001:9001" # for tcp incoming requests
      # environment:
    #   - NIFI_WEB_HTTP_PORT=8080
    #   - NIFI_CLUSTER_IS_NODE=true
    #   - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
    #   - NIFI_ZK_CONNECT_STRING=zookeeper:2181
    #   - NIFI_ELECTION_MAX_WAIT=1 min
