apiVersion: apps/v1
kind: Deployment
metadata:
  # the config deployment to handle depl
  name: haproxy-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: loadbalancer
          resources:
            limits:
              memory: "128Mi"
              cpu: "1500m"
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 9000
              name: https
            - containerPort: 2777
              name: stats

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - port: 3000
      targetPort: 5000
