apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifisingle-deployemnt
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
        - name: nifi
          resources:
            limits:
              memory: "128Mi"
              cpu: "1500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
spec:
  selector:
    app: nifi
  ports:
    - port: 4000
      targetPort: 80
